package:
  name: "scorect"
  version: "0.0.1"

source:
  git_rev: v0.0.1
  git_url: https://github.com/asaravia-butler/scoreCT

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - pandas
    - numpy
    - requests
    - matplotlib
    - seaborn

about:
  home: https://github.com/asaravia-butler/scoreCT
  license: MIT
  license_familY: MIT
  license_file: LICENSE.md
  summary: "Automated cell type annotation for scRNA-seq data in Scanpy"

extra:
  recipe-maintainers:
    - LucasESBS
